<?xml version="1.0" encoding="UTF-8"?>
<?xml-model href="http://www.daisy.org/ns/xprocspec/xprocspec.rng" type="application/xml" schematypens="http://relaxng.org/ns/structure/1.0"?>
<x:description xmlns:c="http://www.w3.org/ns/xproc-step" xmlns:x="http://www.daisy.org/ns/xprocspec" xmlns:e="http://example.net/ns" script="../steps/error.xpl">

    <x:scenario label="error">
        <x:call step="e:error"/>

        <!-- test getting errors document (should be c:errors when errors) -->
        <x:context label="the error document">
            <x:document type="errors"/>
        </x:context>
        <x:expect label="the error document must have c:errors as its root element" type="xpath" test="/c:errors"/>
        <x:expect label="the error document must match the expected error document" type="compare"
            pending="this does not work in the current version of calabash; catching errors that are thrown from invoked
            steps does not work properly, only errors that are thrown directly inside the try/group-element.
            See if it works in the newest version of calabash before submitting an issue report.">
            <x:document type="inline">
                <c:errors>
                    <c:error code="ex:TODO"/>
                </c:errors>
            </x:document>
        </x:expect>
    </x:scenario>

</x:description>
